# Generated by Django 5.0.3 on 2024-05-22 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('req_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('req_type', models.CharField(blank=True, max_length=300, null=True)),
                ('app_name', models.CharField(blank=True, max_length=400, null=True)),
                ('event', models.CharField(blank=True, max_length=600, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('req_body', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
